// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by RoboKindChat.vshost.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.robokind.avrogen.speech
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class SpeechConfigRecord : ISpecificRecord, SpeechConfig
	{
		private static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""SpeechConfigRecord"",""namespace"":""org.robokind.avrogen.speech"",""fields"":[{""name"":""speechServiceId"",""type"":""string""},{""name"":""configSourceId"",""type"":""string""},{""name"":""voiceName"",""type"":""string""},{""name"":""sampleRate"",""type"":""double""}]}");
		private string _speechServiceId;
		private string _configSourceId;
		private string _voiceName;
		private double _sampleRate;
		public virtual Schema Schema
		{
			get
			{
				return SpeechConfigRecord._SCHEMA;
			}
		}
		public string speechServiceId
		{
			get
			{
				return this._speechServiceId;
			}
			set
			{
				this._speechServiceId = value;
			}
		}
		public string configSourceId
		{
			get
			{
				return this._configSourceId;
			}
			set
			{
				this._configSourceId = value;
			}
		}
		public string voiceName
		{
			get
			{
				return this._voiceName;
			}
			set
			{
				this._voiceName = value;
			}
		}
		public double sampleRate
		{
			get
			{
				return this._sampleRate;
			}
			set
			{
				this._sampleRate = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.speechServiceId;
			case 1: return this.configSourceId;
			case 2: return this.voiceName;
			case 3: return this.sampleRate;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.speechServiceId = (System.String)fieldValue; break;
			case 1: this.configSourceId = (System.String)fieldValue; break;
			case 2: this.voiceName = (System.String)fieldValue; break;
			case 3: this.sampleRate = (System.Double)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
