// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by RoboKindChat.vshost.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.robokind.avrogen.vision
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public interface Camera
	{
		Schema Schema
		{
			get;
		}
		string brokerAddress
		{
			get;
		}
		string connectionOptions
		{
			get;
		}
		string destination
		{
			get;
		}
		int cameraNumber
		{
			get;
		}
		int frameLength
		{
			get;
		}
		int imageWidth
		{
			get;
		}
		int imageHeight
		{
			get;
		}
		int imageChannels
		{
			get;
		}
	}
}
