// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by RoboKindChat.vshost.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.robokind.avrogen.vision
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public interface ImageDisplay
	{
		Schema Schema
		{
			get;
		}
		string brokerAddress
		{
			get;
		}
		string connectionOptions
		{
			get;
		}
		string imageQueue
		{
			get;
		}
		string annotationQueue
		{
			get;
		}
		int drawRate
		{
			get;
		}
		string windowName
		{
			get;
		}
	}
}
