// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by RoboKindChat.vshost.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.robokind.avrogen.vision
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public interface ImageRegionList
	{
		Schema Schema
		{
			get;
		}
		string imageSourceId
		{
			get;
		}
		long imageId
		{
			get;
		}
		long imageTimestampMillisecUTC
		{
			get;
		}
		string imageProcessorId
		{
			get;
		}
		long imageRegionsId
		{
			get;
		}
		long processorStartTimestampMillisecUTC
		{
			get;
		}
		long processorCompleteTimestampMillisecUTC
		{
			get;
		}
		IList<org.robokind.avrogen.vision.ImageRegionRecord> regions
		{
			get;
		}
	}
}
