// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by RoboKindChat.vshost.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.robokind.avrogen.vision
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class FaceDetectConfig : ISpecificRecord, FaceDetect
	{
		private static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""FaceDetectConfig"",""namespace"":""org.robokind.avrogen.vision"",""fields"":[{""name"":""brokerAddress"",""type"":""string""},{""name"":""connectionOptions"",""type"":""string""},{""name"":""receivingAddress"",""type"":""string""},{""name"":""resultsAddress"",""type"":""string""},{""name"":""haarFileLocation"",""type"":""string""},{""name"":""scaleFactor"",""type"":""double""},{""name"":""neighbors"",""type"":""int""},{""name"":""haarFlags"",""type"":""int""},{""name"":""minFaceWidth"",""type"":""int""},{""name"":""minFaceHeight"",""type"":""int""}]}");
		private string _brokerAddress;
		private string _connectionOptions;
		private string _receivingAddress;
		private string _resultsAddress;
		private string _haarFileLocation;
		private double _scaleFactor;
		private int _neighbors;
		private int _haarFlags;
		private int _minFaceWidth;
		private int _minFaceHeight;
		public virtual Schema Schema
		{
			get
			{
				return FaceDetectConfig._SCHEMA;
			}
		}
		public string brokerAddress
		{
			get
			{
				return this._brokerAddress;
			}
			set
			{
				this._brokerAddress = value;
			}
		}
		public string connectionOptions
		{
			get
			{
				return this._connectionOptions;
			}
			set
			{
				this._connectionOptions = value;
			}
		}
		public string receivingAddress
		{
			get
			{
				return this._receivingAddress;
			}
			set
			{
				this._receivingAddress = value;
			}
		}
		public string resultsAddress
		{
			get
			{
				return this._resultsAddress;
			}
			set
			{
				this._resultsAddress = value;
			}
		}
		public string haarFileLocation
		{
			get
			{
				return this._haarFileLocation;
			}
			set
			{
				this._haarFileLocation = value;
			}
		}
		public double scaleFactor
		{
			get
			{
				return this._scaleFactor;
			}
			set
			{
				this._scaleFactor = value;
			}
		}
		public int neighbors
		{
			get
			{
				return this._neighbors;
			}
			set
			{
				this._neighbors = value;
			}
		}
		public int haarFlags
		{
			get
			{
				return this._haarFlags;
			}
			set
			{
				this._haarFlags = value;
			}
		}
		public int minFaceWidth
		{
			get
			{
				return this._minFaceWidth;
			}
			set
			{
				this._minFaceWidth = value;
			}
		}
		public int minFaceHeight
		{
			get
			{
				return this._minFaceHeight;
			}
			set
			{
				this._minFaceHeight = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.brokerAddress;
			case 1: return this.connectionOptions;
			case 2: return this.receivingAddress;
			case 3: return this.resultsAddress;
			case 4: return this.haarFileLocation;
			case 5: return this.scaleFactor;
			case 6: return this.neighbors;
			case 7: return this.haarFlags;
			case 8: return this.minFaceWidth;
			case 9: return this.minFaceHeight;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.brokerAddress = (System.String)fieldValue; break;
			case 1: this.connectionOptions = (System.String)fieldValue; break;
			case 2: this.receivingAddress = (System.String)fieldValue; break;
			case 3: this.resultsAddress = (System.String)fieldValue; break;
			case 4: this.haarFileLocation = (System.String)fieldValue; break;
			case 5: this.scaleFactor = (System.Double)fieldValue; break;
			case 6: this.neighbors = (System.Int32)fieldValue; break;
			case 7: this.haarFlags = (System.Int32)fieldValue; break;
			case 8: this.minFaceWidth = (System.Int32)fieldValue; break;
			case 9: this.minFaceHeight = (System.Int32)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
