// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by RoboKindChat.vshost.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.robokind.avrogen.vision
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public interface FaceDetect
	{
		Schema Schema
		{
			get;
		}
		string brokerAddress
		{
			get;
		}
		string connectionOptions
		{
			get;
		}
		string receivingAddress
		{
			get;
		}
		string resultsAddress
		{
			get;
		}
		string haarFileLocation
		{
			get;
		}
		double scaleFactor
		{
			get;
		}
		int neighbors
		{
			get;
		}
		int haarFlags
		{
			get;
		}
		int minFaceWidth
		{
			get;
		}
		int minFaceHeight
		{
			get;
		}
	}
}
