// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by RoboKindChat.vshost.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.robokind.avrogen.vision
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class ImageDisplayConfig : ISpecificRecord, ImageDisplay
	{
		private static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""ImageDisplayConfig"",""namespace"":""org.robokind.avrogen.vision"",""fields"":[{""name"":""brokerAddress"",""type"":""string""},{""name"":""connectionOptions"",""type"":""string""},{""name"":""imageQueue"",""type"":""string""},{""name"":""annotationQueue"",""type"":""string""},{""name"":""drawRate"",""type"":""int""},{""name"":""windowName"",""type"":""string""}]}");
		private string _brokerAddress;
		private string _connectionOptions;
		private string _imageQueue;
		private string _annotationQueue;
		private int _drawRate;
		private string _windowName;
		public virtual Schema Schema
		{
			get
			{
				return ImageDisplayConfig._SCHEMA;
			}
		}
		public string brokerAddress
		{
			get
			{
				return this._brokerAddress;
			}
			set
			{
				this._brokerAddress = value;
			}
		}
		public string connectionOptions
		{
			get
			{
				return this._connectionOptions;
			}
			set
			{
				this._connectionOptions = value;
			}
		}
		public string imageQueue
		{
			get
			{
				return this._imageQueue;
			}
			set
			{
				this._imageQueue = value;
			}
		}
		public string annotationQueue
		{
			get
			{
				return this._annotationQueue;
			}
			set
			{
				this._annotationQueue = value;
			}
		}
		public int drawRate
		{
			get
			{
				return this._drawRate;
			}
			set
			{
				this._drawRate = value;
			}
		}
		public string windowName
		{
			get
			{
				return this._windowName;
			}
			set
			{
				this._windowName = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.brokerAddress;
			case 1: return this.connectionOptions;
			case 2: return this.imageQueue;
			case 3: return this.annotationQueue;
			case 4: return this.drawRate;
			case 5: return this.windowName;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.brokerAddress = (System.String)fieldValue; break;
			case 1: this.connectionOptions = (System.String)fieldValue; break;
			case 2: this.imageQueue = (System.String)fieldValue; break;
			case 3: this.annotationQueue = (System.String)fieldValue; break;
			case 4: this.drawRate = (System.Int32)fieldValue; break;
			case 5: this.windowName = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
