// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by RoboKindChat.vshost.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.robokind.avrogen.vision
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public interface ImageRegion
	{
		Schema Schema
		{
			get;
		}
		int regionId
		{
			get;
		}
		int x
		{
			get;
		}
		int y
		{
			get;
		}
		int width
		{
			get;
		}
		int height
		{
			get;
		}
	}
}
