// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by RoboKindChat.vshost.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.robokind.avrogen.vision
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class ImageRecord : ISpecificRecord, Image
	{
		private static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""ImageRecord"",""namespace"":""org.robokind.avrogen.vision"",""fields"":[{""name"":""imageSourceId"",""type"":""string""},{""name"":""imageId"",""type"":""long""},{""name"":""imageTimestampMillisecUTC"",""type"":""long""},{""name"":""width"",""type"":""int""},{""name"":""height"",""type"":""int""},{""name"":""nChannels"",""type"":""int""},{""name"":""widthStep"",""type"":""int""},{""name"":""data"",""type"":""bytes""}]}");
		private string _imageSourceId;
		private long _imageId;
		private long _imageTimestampMillisecUTC;
		private int _width;
		private int _height;
		private int _nChannels;
		private int _widthStep;
		private byte[] _data;
		public virtual Schema Schema
		{
			get
			{
				return ImageRecord._SCHEMA;
			}
		}
		public string imageSourceId
		{
			get
			{
				return this._imageSourceId;
			}
			set
			{
				this._imageSourceId = value;
			}
		}
		public long imageId
		{
			get
			{
				return this._imageId;
			}
			set
			{
				this._imageId = value;
			}
		}
		public long imageTimestampMillisecUTC
		{
			get
			{
				return this._imageTimestampMillisecUTC;
			}
			set
			{
				this._imageTimestampMillisecUTC = value;
			}
		}
		public int width
		{
			get
			{
				return this._width;
			}
			set
			{
				this._width = value;
			}
		}
		public int height
		{
			get
			{
				return this._height;
			}
			set
			{
				this._height = value;
			}
		}
		public int nChannels
		{
			get
			{
				return this._nChannels;
			}
			set
			{
				this._nChannels = value;
			}
		}
		public int widthStep
		{
			get
			{
				return this._widthStep;
			}
			set
			{
				this._widthStep = value;
			}
		}
		public byte[] data
		{
			get
			{
				return this._data;
			}
			set
			{
				this._data = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.imageSourceId;
			case 1: return this.imageId;
			case 2: return this.imageTimestampMillisecUTC;
			case 3: return this.width;
			case 4: return this.height;
			case 5: return this.nChannels;
			case 6: return this.widthStep;
			case 7: return this.data;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.imageSourceId = (System.String)fieldValue; break;
			case 1: this.imageId = (System.Int64)fieldValue; break;
			case 2: this.imageTimestampMillisecUTC = (System.Int64)fieldValue; break;
			case 3: this.width = (System.Int32)fieldValue; break;
			case 4: this.height = (System.Int32)fieldValue; break;
			case 5: this.nChannels = (System.Int32)fieldValue; break;
			case 6: this.widthStep = (System.Int32)fieldValue; break;
			case 7: this.data = (System.Byte[])fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
