// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by RoboKindChat.vshost.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.robokind.avrogen.vision
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class ImageRegionRecord : ISpecificRecord, ImageRegion
	{
		private static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"ImageRegionRecord\",\"namespace\":\"org.robokind.avrogen.vis" +
				"ion\",\"fields\":[{\"name\":\"regionId\",\"type\":\"int\"},{\"name\":\"x\",\"type\":\"int\"},{\"name" +
				"\":\"y\",\"type\":\"int\"},{\"name\":\"width\",\"type\":\"int\"},{\"name\":\"height\",\"type\":\"int\"}" +
				"]}");
		private int _regionId;
		private int _x;
		private int _y;
		private int _width;
		private int _height;
		public virtual Schema Schema
		{
			get
			{
				return ImageRegionRecord._SCHEMA;
			}
		}
		public int regionId
		{
			get
			{
				return this._regionId;
			}
			set
			{
				this._regionId = value;
			}
		}
		public int x
		{
			get
			{
				return this._x;
			}
			set
			{
				this._x = value;
			}
		}
		public int y
		{
			get
			{
				return this._y;
			}
			set
			{
				this._y = value;
			}
		}
		public int width
		{
			get
			{
				return this._width;
			}
			set
			{
				this._width = value;
			}
		}
		public int height
		{
			get
			{
				return this._height;
			}
			set
			{
				this._height = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.regionId;
			case 1: return this.x;
			case 2: return this.y;
			case 3: return this.width;
			case 4: return this.height;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.regionId = (System.Int32)fieldValue; break;
			case 1: this.x = (System.Int32)fieldValue; break;
			case 2: this.y = (System.Int32)fieldValue; break;
			case 3: this.width = (System.Int32)fieldValue; break;
			case 4: this.height = (System.Int32)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
