// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by RoboKindChat.vshost.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.robokind.avrogen.speechrec
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class SpeechRecConfigRecord : ISpecificRecord, SpeechRecConfig
	{
		private static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""SpeechRecConfigRecord"",""namespace"":""org.robokind.avrogen.speechrec"",""fields"":[{""name"":""speechRecServiceId"",""type"":""string""},{""name"":""configSourceId"",""type"":""string""},{""name"":""timestampMillisecUTC"",""type"":""long""},{""name"":""vocabLocation"",""type"":""string""}]}");
		private string _speechRecServiceId;
		private string _configSourceId;
		private long _timestampMillisecUTC;
		private string _vocabLocation;
		public virtual Schema Schema
		{
			get
			{
				return SpeechRecConfigRecord._SCHEMA;
			}
		}
		public string speechRecServiceId
		{
			get
			{
				return this._speechRecServiceId;
			}
			set
			{
				this._speechRecServiceId = value;
			}
		}
		public string configSourceId
		{
			get
			{
				return this._configSourceId;
			}
			set
			{
				this._configSourceId = value;
			}
		}
		public long timestampMillisecUTC
		{
			get
			{
				return this._timestampMillisecUTC;
			}
			set
			{
				this._timestampMillisecUTC = value;
			}
		}
		public string vocabLocation
		{
			get
			{
				return this._vocabLocation;
			}
			set
			{
				this._vocabLocation = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.speechRecServiceId;
			case 1: return this.configSourceId;
			case 2: return this.timestampMillisecUTC;
			case 3: return this.vocabLocation;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.speechRecServiceId = (System.String)fieldValue; break;
			case 1: this.configSourceId = (System.String)fieldValue; break;
			case 2: this.timestampMillisecUTC = (System.Int64)fieldValue; break;
			case 3: this.vocabLocation = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
