// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by RoboKindChat.vshost.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.robokind.avrogen.audio
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public interface WavPlayerConfig
	{
		Schema Schema
		{
			get;
		}
		string wavPlayerId
		{
			get;
		}
		string wavLocation
		{
			get;
		}
		long startTimeMicrosec
		{
			get;
		}
		long stopTimeMicrosec
		{
			get;
		}
		long startDelayMillisec
		{
			get;
		}
	}
}
