// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by RoboKindChat.vshost.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.robokind.avrogen.speech.viseme
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class VisemeBindingConfigRecord : ISpecificRecord, VisemeBindingConfig
	{
		private static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""VisemeBindingConfigRecord"",""namespace"":""org.robokind.avrogen.speech.viseme"",""fields"":[{""name"":""bindingId"",""type"":""int""},{""name"":""visemeBindings"",""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""VisemePositionRecord"",""namespace"":""org.robokind.avrogen.speech.viseme"",""fields"":[{""name"":""visemeId"",""type"":""int""},{""name"":""position"",""type"":""double""}]}}}]}");
		private int _bindingId;
		private IList<org.robokind.avrogen.speech.viseme.VisemePositionRecord> _visemeBindings;
		public virtual Schema Schema
		{
			get
			{
				return VisemeBindingConfigRecord._SCHEMA;
			}
		}
		public int bindingId
		{
			get
			{
				return this._bindingId;
			}
			set
			{
				this._bindingId = value;
			}
		}
		public IList<org.robokind.avrogen.speech.viseme.VisemePositionRecord> visemeBindings
		{
			get
			{
				return this._visemeBindings;
			}
			set
			{
				this._visemeBindings = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.bindingId;
			case 1: return this.visemeBindings;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.bindingId = (System.Int32)fieldValue; break;
			case 1: this.visemeBindings = (IList<org.robokind.avrogen.speech.viseme.VisemePositionRecord>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
