// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by RoboKindChat.vshost.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.robokind.avrogen.speech.viseme
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class VisemePositionRecord : ISpecificRecord, VisemePosition
	{
		private static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"VisemePositionRecord\",\"namespace\":\"org.robokind.avrogen." +
				"speech.viseme\",\"fields\":[{\"name\":\"visemeId\",\"type\":\"int\"},{\"name\":\"position\",\"ty" +
				"pe\":\"double\"}]}");
		private int _visemeId;
		private double _position;
		public virtual Schema Schema
		{
			get
			{
				return VisemePositionRecord._SCHEMA;
			}
		}
		public int visemeId
		{
			get
			{
				return this._visemeId;
			}
			set
			{
				this._visemeId = value;
			}
		}
		public double position
		{
			get
			{
				return this._position;
			}
			set
			{
				this._position = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.visemeId;
			case 1: return this.position;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.visemeId = (System.Int32)fieldValue; break;
			case 1: this.position = (System.Double)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
