// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by RoboKindChat.vshost.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.robokind.avrogen.animation
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class AnimationRecord : ISpecificRecord, Animation
	{
		private static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""AnimationRecord"",""namespace"":""org.robokind.avrogen.animation"",""fields"":[{""name"":""name"",""type"":""string""},{""name"":""versionNumber"",""type"":""string""},{""name"":""stopTime"",""type"":[""null"",""long""]},{""name"":""startTime"",""type"":[""null"",""long""]},{""name"":""channels"",""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""ChannelRecord"",""namespace"":""org.robokind.avrogen.animation"",""fields"":[{""name"":""name"",""type"":""string""},{""name"":""channelId"",""type"":""int""},{""name"":""stopTime"",""type"":[""null"",""long""]},{""name"":""startTime"",""type"":[""null"",""long""]},{""name"":""motionPaths"",""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""MotionPathRecord"",""namespace"":""org.robokind.avrogen.animation"",""fields"":[{""name"":""name"",""type"":""string""},{""name"":""motionPathId"",""type"":""int""},{""name"":""startTime"",""type"":[""null"",""long""]},{""name"":""stopTime"",""type"":[""null"",""long""]},{""name"":""interpolator"",""type"":{""type"":""record"",""name"":""InterpolatorTypeRecord"",""namespace"":""org.robokind.avrogen.animation"",""fields"":[{""name"":""name"",""type"":""string""},{""name"":""versionNumber"",""type"":""string""}]}},{""name"":""controlPoints"",""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""ControlPointRecord"",""namespace"":""org.robokind.avrogen.animation"",""fields"":[{""name"":""time"",""type"":""long""},{""name"":""position"",""type"":""double""}]}}}]}}}]}}}]}");
		private string _name;
		private string _versionNumber;
		private System.Nullable<long> _stopTime;
		private System.Nullable<long> _startTime;
		private IList<org.robokind.avrogen.animation.ChannelRecord> _channels;
		public virtual Schema Schema
		{
			get
			{
				return AnimationRecord._SCHEMA;
			}
		}
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		public string versionNumber
		{
			get
			{
				return this._versionNumber;
			}
			set
			{
				this._versionNumber = value;
			}
		}
		public System.Nullable<long> stopTime
		{
			get
			{
				return this._stopTime;
			}
			set
			{
				this._stopTime = value;
			}
		}
		public System.Nullable<long> startTime
		{
			get
			{
				return this._startTime;
			}
			set
			{
				this._startTime = value;
			}
		}
		public IList<org.robokind.avrogen.animation.ChannelRecord> channels
		{
			get
			{
				return this._channels;
			}
			set
			{
				this._channels = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.name;
			case 1: return this.versionNumber;
			case 2: return this.stopTime;
			case 3: return this.startTime;
			case 4: return this.channels;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.name = (System.String)fieldValue; break;
			case 1: this.versionNumber = (System.String)fieldValue; break;
			case 2: this.stopTime = (System.Nullable<long>)fieldValue; break;
			case 3: this.startTime = (System.Nullable<long>)fieldValue; break;
			case 4: this.channels = (IList<org.robokind.avrogen.animation.ChannelRecord>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
