// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by RoboKindChat.vshost.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.robokind.avrogen.animation
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class ControlPointRecord : ISpecificRecord, ControlPoint
	{
		private static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"ControlPointRecord\",\"namespace\":\"org.robokind.avrogen.an" +
				"imation\",\"fields\":[{\"name\":\"time\",\"type\":\"long\"},{\"name\":\"position\",\"type\":\"doub" +
				"le\"}]}");
		private long _time;
		private double _position;
		public virtual Schema Schema
		{
			get
			{
				return ControlPointRecord._SCHEMA;
			}
		}
		public long time
		{
			get
			{
				return this._time;
			}
			set
			{
				this._time = value;
			}
		}
		public double position
		{
			get
			{
				return this._position;
			}
			set
			{
				this._position = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.time;
			case 1: return this.position;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.time = (System.Int64)fieldValue; break;
			case 1: this.position = (System.Double)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
