// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by RoboKindChat.vshost.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.robokind.avrogen.animation
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class PlayRequestRecord : ISpecificRecord, PlayRequest
	{
		private static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""PlayRequestRecord"",""namespace"":""org.robokind.avrogen.animation"",""fields"":[{""name"":""sourceId"",""type"":""string""},{""name"":""destinationId"",""type"":""string""},{""name"":""currentTimeMillisec"",""type"":""long""},{""name"":""animationName"",""type"":""string""},{""name"":""animationVersionNumber"",""type"":[""null"",""string""]}]}");
		private string _sourceId;
		private string _destinationId;
		private long _currentTimeMillisec;
		private string _animationName;
		private string _animationVersionNumber;
		public virtual Schema Schema
		{
			get
			{
				return PlayRequestRecord._SCHEMA;
			}
		}
		public string sourceId
		{
			get
			{
				return this._sourceId;
			}
			set
			{
				this._sourceId = value;
			}
		}
		public string destinationId
		{
			get
			{
				return this._destinationId;
			}
			set
			{
				this._destinationId = value;
			}
		}
		public long currentTimeMillisec
		{
			get
			{
				return this._currentTimeMillisec;
			}
			set
			{
				this._currentTimeMillisec = value;
			}
		}
		public string animationName
		{
			get
			{
				return this._animationName;
			}
			set
			{
				this._animationName = value;
			}
		}
		public string animationVersionNumber
		{
			get
			{
				return this._animationVersionNumber;
			}
			set
			{
				this._animationVersionNumber = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.sourceId;
			case 1: return this.destinationId;
			case 2: return this.currentTimeMillisec;
			case 3: return this.animationName;
			case 4: return this.animationVersionNumber;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.sourceId = (System.String)fieldValue; break;
			case 1: this.destinationId = (System.String)fieldValue; break;
			case 2: this.currentTimeMillisec = (System.Int64)fieldValue; break;
			case 3: this.animationName = (System.String)fieldValue; break;
			case 4: this.animationVersionNumber = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
