// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by RoboKindChat.vshost.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.robokind.avrogen.motion
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class JointIdRecord : ISpecificRecord, JointId
	{
		private static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"JointIdRecord\",\"namespace\":\"org.robokind.avrogen.motion\"" +
				",\"fields\":[{\"name\":\"robotId\",\"type\":\"string\"},{\"name\":\"jointId\",\"type\":\"int\"}]}");
		private string _robotId;
		private int _jointId;
		public virtual Schema Schema
		{
			get
			{
				return JointIdRecord._SCHEMA;
			}
		}
		public string robotId
		{
			get
			{
				return this._robotId;
			}
			set
			{
				this._robotId = value;
			}
		}
		public int jointId
		{
			get
			{
				return this._jointId;
			}
			set
			{
				this._jointId = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.robotId;
			case 1: return this.jointId;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.robotId = (System.String)fieldValue; break;
			case 1: this.jointId = (System.Int32)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
