// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by RoboKindChat.vshost.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.robokind.avrogen.motion
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class SynchronizedJointConfigRecord : ISpecificRecord, SynchronizedJointConfig
	{
		private static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"SynchronizedJointConfigRecord\",\"namespace\":\"org.robokind" +
				".avrogen.motion\",\"fields\":[{\"name\":\"jointId\",\"type\":\"int\"},{\"name\":\"name\",\"type\"" +
				":\"string\"},{\"name\":\"defaultPosition\",\"type\":[\"double\",\"null\"]}]}");
		private int _jointId;
		private string _name;
		private System.Nullable<double> _defaultPosition;
		public virtual Schema Schema
		{
			get
			{
				return SynchronizedJointConfigRecord._SCHEMA;
			}
		}
		public int jointId
		{
			get
			{
				return this._jointId;
			}
			set
			{
				this._jointId = value;
			}
		}
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		public System.Nullable<double> defaultPosition
		{
			get
			{
				return this._defaultPosition;
			}
			set
			{
				this._defaultPosition = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.jointId;
			case 1: return this.name;
			case 2: return this.defaultPosition;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.jointId = (System.Int32)fieldValue; break;
			case 1: this.name = (System.String)fieldValue; break;
			case 2: this.defaultPosition = (System.Nullable<double>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
