//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cogbot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cogbot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        internal static System.Drawing.Bitmap add_16
        {
            get
            {
                object obj = ResourceManager.GetObject("add_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap add_B16
        {
            get
            {
                object obj = ResourceManager.GetObject("add_B16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap applications_16
        {
            get
            {
                object obj = ResourceManager.GetObject("applications_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap applications_32
        {
            get
            {
                object obj = ResourceManager.GetObject("applications_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap arrow_forward_16
        {
            get
            {
                object obj = ResourceManager.GetObject("arrow_forward_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap arrow_up_16
        {
            get
            {
                object obj = ResourceManager.GetObject("arrow_up_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Audio_CD_16
        {
            get
            {
                object obj = ResourceManager.GetObject("Audio_CD_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap computer_16
        {
            get
            {
                object obj = ResourceManager.GetObject("computer_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap copy_16
        {
            get
            {
                object obj = ResourceManager.GetObject("copy_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap cut_16
        {
            get
            {
                object obj = ResourceManager.GetObject("cut_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap delete_16
        {
            get
            {
                object obj = ResourceManager.GetObject("delete_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap documents_16
        {
            get
            {
                object obj = ResourceManager.GetObject("documents_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap documents_32
        {
            get
            {
                object obj = ResourceManager.GetObject("documents_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap down
        {
            get
            {
                object obj = ResourceManager.GetObject("down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Entire_Network_16
        {
            get
            {
                object obj = ResourceManager.GetObject("Entire_Network_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap folder_closed_16
        {
            get
            {
                object obj = ResourceManager.GetObject("folder_closed_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap folder_open_16
        {
            get
            {
                object obj = ResourceManager.GetObject("folder_open_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap freeze
        {
            get
            {
                object obj = ResourceManager.GetObject("freeze", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap GreenOrb_16
        {
            get
            {
                object obj = ResourceManager.GetObject("GreenOrb_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap GreenOrbFaded_16
        {
            get
            {
                object obj = ResourceManager.GetObject("GreenOrbFaded_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Help_and_Support_16
        {
            get
            {
                object obj = ResourceManager.GetObject("Help_and_Support_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap lsl_scripts_16
        {
            get
            {
                object obj = ResourceManager.GetObject("lsl_scripts_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap METAbolt_icon
        {
            get
            {
                object obj = ResourceManager.GetObject("METAbolt_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Legolas Luke.
        /// </summary>
        internal static string METAboltAuthor
        {
            get
            {
                return ResourceManager.GetString("METAboltAuthor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to METAbolt.
        /// </summary>
        internal static string METAboltTitle
        {
            get
            {
                return ResourceManager.GetString("METAboltTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 0.9.1.12 (BETA).
        /// </summary>
        internal static string METAboltVersion
        {
            get
            {
                return ResourceManager.GetString("METAboltVersion", resourceCulture);
            }
        }

        internal static System.Drawing.Bitmap My_Documents_16
        {
            get
            {
                object obj = ResourceManager.GetObject("My_Documents_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap paste_16
        {
            get
            {
                object obj = ResourceManager.GetObject("paste_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap save_16
        {
            get
            {
                object obj = ResourceManager.GetObject("save_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap save_32
        {
            get
            {
                object obj = ResourceManager.GetObject("save_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Scheduled_Tasks_16
        {
            get
            {
                object obj = ResourceManager.GetObject("Scheduled_Tasks_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Scheduled_Tasks_161
        {
            get
            {
                object obj = ResourceManager.GetObject("Scheduled_Tasks_161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Search_16
        {
            get
            {
                object obj = ResourceManager.GetObject("Search_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Search_32
        {
            get
            {
                object obj = ResourceManager.GetObject("Search_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap security_16
        {
            get
            {
                object obj = ResourceManager.GetObject("security_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap security_32
        {
            get
            {
                object obj = ResourceManager.GetObject("security_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Settings_16
        {
            get
            {
                object obj = ResourceManager.GetObject("Settings_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Settings_32
        {
            get
            {
                object obj = ResourceManager.GetObject("Settings_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap System_16
        {
            get
            {
                object obj = ResourceManager.GetObject("System_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap up
        {
            get
            {
                object obj = ResourceManager.GetObject("up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Url_History_16
        {
            get
            {
                object obj = ResourceManager.GetObject("Url_History_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Url_History_161
        {
            get
            {
                object obj = ResourceManager.GetObject("Url_History_161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap wmp
        {
            get
            {
                object obj = ResourceManager.GetObject("wmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Sauver
        {
            get
            {
                try
                {
                    object obj = ResourceManager.GetObject("Sauver", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
                catch (Exception)
                {
                    return null;
                }
            }
        }
    }
}
