// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by RoboKindChat.vshost.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.robokind.avrogen.animation
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class AnimationEventRecord : ISpecificRecord, AnimationEvent
	{
		private static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"AnimationEventRecord\",\"namespace\":\"org.robokind.avrogen." +
				"animation\",\"fields\":[{\"name\":\"sourceId\",\"type\":\"string\"},{\"name\":\"destinationId\"" +
				",\"type\":\"string\"},{\"name\":\"currentTimeMillisec\",\"type\":\"long\"},{\"name\":\"animatio" +
				"n\",\"type\":{\"type\":\"record\",\"name\":\"AnimationRecord\",\"namespace\":\"org.robokind.av" +
				"rogen.animation\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"versionNumbe" +
				"r\",\"type\":\"string\"},{\"name\":\"stopTime\",\"type\":[\"null\",\"long\"]},{\"name\":\"startTim" +
				"e\",\"type\":[\"null\",\"long\"]},{\"name\":\"channels\",\"type\":{\"type\":\"array\",\"items\":{\"t" +
				"ype\":\"record\",\"name\":\"ChannelRecord\",\"namespace\":\"org.robokind.avrogen.animation" +
				"\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"channelId\",\"type\":\"int\"},{\"" +
				"name\":\"stopTime\",\"type\":[\"null\",\"long\"]},{\"name\":\"startTime\",\"type\":[\"null\",\"lon" +
				"g\"]},{\"name\":\"motionPaths\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name" +
				"\":\"MotionPathRecord\",\"namespace\":\"org.robokind.avrogen.animation\",\"fields\":[{\"na" +
				"me\":\"name\",\"type\":\"string\"},{\"name\":\"motionPathId\",\"type\":\"int\"},{\"name\":\"startT" +
				"ime\",\"type\":[\"null\",\"long\"]},{\"name\":\"stopTime\",\"type\":[\"null\",\"long\"]},{\"name\":" +
				"\"interpolator\",\"type\":{\"type\":\"record\",\"name\":\"InterpolatorTypeRecord\",\"namespac" +
				"e\":\"org.robokind.avrogen.animation\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"" +
				"name\":\"versionNumber\",\"type\":\"string\"}]}},{\"name\":\"controlPoints\",\"type\":{\"type\"" +
				":\"array\",\"items\":{\"type\":\"record\",\"name\":\"ControlPointRecord\",\"namespace\":\"org.r" +
				"obokind.avrogen.animation\",\"fields\":[{\"name\":\"time\",\"type\":\"long\"},{\"name\":\"posi" +
				"tion\",\"type\":\"double\"}]}}}]}}}]}}}]}}]}");
		private string _sourceId;
		private string _destinationId;
		private long _currentTimeMillisec;
		private org.robokind.avrogen.animation.AnimationRecord _animation;
		public virtual Schema Schema
		{
			get
			{
				return AnimationEventRecord._SCHEMA;
			}
		}
		public string sourceId
		{
			get
			{
				return this._sourceId;
			}
			set
			{
				this._sourceId = value;
			}
		}
		public string destinationId
		{
			get
			{
				return this._destinationId;
			}
			set
			{
				this._destinationId = value;
			}
		}
		public long currentTimeMillisec
		{
			get
			{
				return this._currentTimeMillisec;
			}
			set
			{
				this._currentTimeMillisec = value;
			}
		}
		public org.robokind.avrogen.animation.AnimationRecord animation
		{
			get
			{
				return this._animation;
			}
			set
			{
				this._animation = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.sourceId;
			case 1: return this.destinationId;
			case 2: return this.currentTimeMillisec;
			case 3: return this.animation;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.sourceId = (System.String)fieldValue; break;
			case 1: this.destinationId = (System.String)fieldValue; break;
			case 2: this.currentTimeMillisec = (System.Int64)fieldValue; break;
			case 3: this.animation = (org.robokind.avrogen.animation.AnimationRecord)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
