// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by RoboKindChat.vshost.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.robokind.avrogen.animation
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class InterpolatorTypeRecord : ISpecificRecord, InterpolatorType
	{
		private static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"InterpolatorTypeRecord\",\"namespace\":\"org.robokind.avroge" +
				"n.animation\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"versionNumber\",\"" +
				"type\":\"string\"}]}");
		private string _name;
		private string _versionNumber;
		public virtual Schema Schema
		{
			get
			{
				return InterpolatorTypeRecord._SCHEMA;
			}
		}
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		public string versionNumber
		{
			get
			{
				return this._versionNumber;
			}
			set
			{
				this._versionNumber = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.name;
			case 1: return this.versionNumber;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.name = (System.String)fieldValue; break;
			case 1: this.versionNumber = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
