// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by RoboKindChat.vshost.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.robokind.avrogen.motion
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class JointDefinitionRecord : ISpecificRecord, JointDefinition
	{
		private static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""JointDefinitionRecord"",""namespace"":""org.robokind.avrogen.motion"",""fields"":[{""name"":""jointId"",""type"":""int""},{""name"":""name"",""type"":""string""},{""name"":""defaultPosition"",""type"":""double""},{""name"":""goalPosition"",""type"":""double""},{""name"":""enabled"",""type"":""boolean""}]}");
		private int _jointId;
		private string _name;
		private double _defaultPosition;
		private double _goalPosition;
		private bool _enabled;
		public virtual Schema Schema
		{
			get
			{
				return JointDefinitionRecord._SCHEMA;
			}
		}
		public int jointId
		{
			get
			{
				return this._jointId;
			}
			set
			{
				this._jointId = value;
			}
		}
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		public double defaultPosition
		{
			get
			{
				return this._defaultPosition;
			}
			set
			{
				this._defaultPosition = value;
			}
		}
		public double goalPosition
		{
			get
			{
				return this._goalPosition;
			}
			set
			{
				this._goalPosition = value;
			}
		}
		public bool enabled
		{
			get
			{
				return this._enabled;
			}
			set
			{
				this._enabled = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.jointId;
			case 1: return this.name;
			case 2: return this.defaultPosition;
			case 3: return this.goalPosition;
			case 4: return this.enabled;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.jointId = (System.Int32)fieldValue; break;
			case 1: this.name = (System.String)fieldValue; break;
			case 2: this.defaultPosition = (System.Double)fieldValue; break;
			case 3: this.goalPosition = (System.Double)fieldValue; break;
			case 4: this.enabled = (System.Boolean)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
