// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by RoboKindChat.vshost.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.robokind.avrogen.motion
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class MotionFrameRecord : ISpecificRecord, MotionFrame
	{
		private static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""MotionFrameRecord"",""namespace"":""org.robokind.avrogen.motion"",""fields"":[{""name"":""timestampMillisecUTC"",""type"":""long""},{""name"":""moveDurationMillisec"",""type"":""long""},{""name"":""goalPositions"",""type"":{""type"":""record"",""name"":""RobotPositionMapRecord"",""namespace"":""org.robokind.avrogen.motion"",""fields"":[{""name"":""jointPositions"",""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""JointPositionRecord"",""namespace"":""org.robokind.avrogen.motion"",""fields"":[{""name"":""jointId"",""type"":{""type"":""record"",""name"":""JointIdRecord"",""namespace"":""org.robokind.avrogen.motion"",""fields"":[{""name"":""robotId"",""type"":""string""},{""name"":""jointId"",""type"":""int""}]}},{""name"":""normalizedPosition"",""type"":""double""}]}}}]}},{""name"":""startPositions"",""type"":[""RobotPositionMapRecord"",""null""]}]}");
		private long _timestampMillisecUTC;
		private long _moveDurationMillisec;
		private org.robokind.avrogen.motion.RobotPositionMapRecord _goalPositions;
		private org.robokind.avrogen.motion.RobotPositionMapRecord _startPositions;
		public virtual Schema Schema
		{
			get
			{
				return MotionFrameRecord._SCHEMA;
			}
		}
		public long timestampMillisecUTC
		{
			get
			{
				return this._timestampMillisecUTC;
			}
			set
			{
				this._timestampMillisecUTC = value;
			}
		}
		public long moveDurationMillisec
		{
			get
			{
				return this._moveDurationMillisec;
			}
			set
			{
				this._moveDurationMillisec = value;
			}
		}
		public org.robokind.avrogen.motion.RobotPositionMapRecord goalPositions
		{
			get
			{
				return this._goalPositions;
			}
			set
			{
				this._goalPositions = value;
			}
		}
		public org.robokind.avrogen.motion.RobotPositionMapRecord startPositions
		{
			get
			{
				return this._startPositions;
			}
			set
			{
				this._startPositions = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.timestampMillisecUTC;
			case 1: return this.moveDurationMillisec;
			case 2: return this.goalPositions;
			case 3: return this.startPositions;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.timestampMillisecUTC = (System.Int64)fieldValue; break;
			case 1: this.moveDurationMillisec = (System.Int64)fieldValue; break;
			case 2: this.goalPositions = (org.robokind.avrogen.motion.RobotPositionMapRecord)fieldValue; break;
			case 3: this.startPositions = (org.robokind.avrogen.motion.RobotPositionMapRecord)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
