// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by RoboKindChat.vshost.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.robokind.avrogen.motion
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class MotionFrameEventRecord : ISpecificRecord, MotionFrameEvent
	{
		private static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""MotionFrameEventRecord"",""namespace"":""org.robokind.avrogen.motion"",""fields"":[{""name"":""sourceId"",""type"":""string""},{""name"":""destinationId"",""type"":""string""},{""name"":""currentTimeMillisecUTC"",""type"":""long""},{""name"":""motionFrame"",""type"":{""type"":""record"",""name"":""MotionFrameRecord"",""namespace"":""org.robokind.avrogen.motion"",""fields"":[{""name"":""timestampMillisecUTC"",""type"":""long""},{""name"":""moveDurationMillisec"",""type"":""long""},{""name"":""goalPositions"",""type"":{""type"":""record"",""name"":""RobotPositionMapRecord"",""namespace"":""org.robokind.avrogen.motion"",""fields"":[{""name"":""jointPositions"",""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""JointPositionRecord"",""namespace"":""org.robokind.avrogen.motion"",""fields"":[{""name"":""jointId"",""type"":{""type"":""record"",""name"":""JointIdRecord"",""namespace"":""org.robokind.avrogen.motion"",""fields"":[{""name"":""robotId"",""type"":""string""},{""name"":""jointId"",""type"":""int""}]}},{""name"":""normalizedPosition"",""type"":""double""}]}}}]}},{""name"":""startPositions"",""type"":[""RobotPositionMapRecord"",""null""]}]}}]}");
		private string _sourceId;
		private string _destinationId;
		private long _currentTimeMillisecUTC;
		private org.robokind.avrogen.motion.MotionFrameRecord _motionFrame;
		public virtual Schema Schema
		{
			get
			{
				return MotionFrameEventRecord._SCHEMA;
			}
		}
		public string sourceId
		{
			get
			{
				return this._sourceId;
			}
			set
			{
				this._sourceId = value;
			}
		}
		public string destinationId
		{
			get
			{
				return this._destinationId;
			}
			set
			{
				this._destinationId = value;
			}
		}
		public long currentTimeMillisecUTC
		{
			get
			{
				return this._currentTimeMillisecUTC;
			}
			set
			{
				this._currentTimeMillisecUTC = value;
			}
		}
		public org.robokind.avrogen.motion.MotionFrameRecord motionFrame
		{
			get
			{
				return this._motionFrame;
			}
			set
			{
				this._motionFrame = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.sourceId;
			case 1: return this.destinationId;
			case 2: return this.currentTimeMillisecUTC;
			case 3: return this.motionFrame;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.sourceId = (System.String)fieldValue; break;
			case 1: this.destinationId = (System.String)fieldValue; break;
			case 2: this.currentTimeMillisecUTC = (System.Int64)fieldValue; break;
			case 3: this.motionFrame = (org.robokind.avrogen.motion.MotionFrameRecord)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
