// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by RoboKindChat.vshost.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.robokind.avrogen.motion
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class RobotPositionMapRecord : ISpecificRecord, RobotPositionMap
	{
		private static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""RobotPositionMapRecord"",""namespace"":""org.robokind.avrogen.motion"",""fields"":[{""name"":""jointPositions"",""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""JointPositionRecord"",""namespace"":""org.robokind.avrogen.motion"",""fields"":[{""name"":""jointId"",""type"":{""type"":""record"",""name"":""JointIdRecord"",""namespace"":""org.robokind.avrogen.motion"",""fields"":[{""name"":""robotId"",""type"":""string""},{""name"":""jointId"",""type"":""int""}]}},{""name"":""normalizedPosition"",""type"":""double""}]}}}]}");
		private IList<org.robokind.avrogen.motion.JointPositionRecord> _jointPositions;
		public virtual Schema Schema
		{
			get
			{
				return RobotPositionMapRecord._SCHEMA;
			}
		}
		public IList<org.robokind.avrogen.motion.JointPositionRecord> jointPositions
		{
			get
			{
				return this._jointPositions;
			}
			set
			{
				this._jointPositions = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.jointPositions;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.jointPositions = (IList<org.robokind.avrogen.motion.JointPositionRecord>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
