// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by RoboKindChat.vshost.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.robokind.avrogen.motion
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class RobotDefinitionResponseRecord : ISpecificRecord, RobotDefinitionResponse
	{
		private static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""RobotDefinitionResponseRecord"",""namespace"":""org.robokind.avrogen.motion"",""fields"":[{""name"":""responseHeader"",""type"":{""type"":""record"",""name"":""RobotResponseHeaderRecord"",""namespace"":""org.robokind.avrogen.motion"",""fields"":[{""name"":""robotId"",""type"":""string""},{""name"":""requestSourceId"",""type"":""string""},{""name"":""requestDestinationId"",""type"":""string""},{""name"":""requestType"",""type"":""string""},{""name"":""requestTimestampMillisecUTC"",""type"":""long""},{""name"":""responseTimestampMillisecUTC"",""type"":""long""}]}},{""name"":""connected"",""type"":""boolean""},{""name"":""enabled"",""type"":""boolean""},{""name"":""joints"",""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""JointDefinitionRecord"",""namespace"":""org.robokind.avrogen.motion"",""fields"":[{""name"":""jointId"",""type"":""int""},{""name"":""name"",""type"":""string""},{""name"":""defaultPosition"",""type"":""double""},{""name"":""goalPosition"",""type"":""double""},{""name"":""enabled"",""type"":""boolean""}]}}}]}");
		private org.robokind.avrogen.motion.RobotResponseHeaderRecord _responseHeader;
		private bool _connected;
		private bool _enabled;
		private IList<org.robokind.avrogen.motion.JointDefinitionRecord> _joints;
		public virtual Schema Schema
		{
			get
			{
				return RobotDefinitionResponseRecord._SCHEMA;
			}
		}
		public org.robokind.avrogen.motion.RobotResponseHeaderRecord responseHeader
		{
			get
			{
				return this._responseHeader;
			}
			set
			{
				this._responseHeader = value;
			}
		}
		public bool connected
		{
			get
			{
				return this._connected;
			}
			set
			{
				this._connected = value;
			}
		}
		public bool enabled
		{
			get
			{
				return this._enabled;
			}
			set
			{
				this._enabled = value;
			}
		}
		public IList<org.robokind.avrogen.motion.JointDefinitionRecord> joints
		{
			get
			{
				return this._joints;
			}
			set
			{
				this._joints = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.responseHeader;
			case 1: return this.connected;
			case 2: return this.enabled;
			case 3: return this.joints;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.responseHeader = (org.robokind.avrogen.motion.RobotResponseHeaderRecord)fieldValue; break;
			case 1: this.connected = (System.Boolean)fieldValue; break;
			case 2: this.enabled = (System.Boolean)fieldValue; break;
			case 3: this.joints = (IList<org.robokind.avrogen.motion.JointDefinitionRecord>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
