// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by RoboKindChat.vshost.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.robokind.avrogen.motion
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class SynchronizedRobotConfigRecord : ISpecificRecord, SynchronizedRobotConfig
	{
		private static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""SynchronizedRobotConfigRecord"",""namespace"":""org.robokind.avrogen.motion"",""fields"":[{""name"":""robotId"",""type"":""string""},{""name"":""joints"",""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""SynchronizedJointConfigRecord"",""namespace"":""org.robokind.avrogen.motion"",""fields"":[{""name"":""jointId"",""type"":""int""},{""name"":""name"",""type"":""string""},{""name"":""defaultPosition"",""type"":[""double"",""null""]}]}}}]}");
		private string _robotId;
		private IList<org.robokind.avrogen.motion.SynchronizedJointConfigRecord> _joints;
		public virtual Schema Schema
		{
			get
			{
				return SynchronizedRobotConfigRecord._SCHEMA;
			}
		}
		public string robotId
		{
			get
			{
				return this._robotId;
			}
			set
			{
				this._robotId = value;
			}
		}
		public IList<org.robokind.avrogen.motion.SynchronizedJointConfigRecord> joints
		{
			get
			{
				return this._joints;
			}
			set
			{
				this._joints = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.robotId;
			case 1: return this.joints;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.robotId = (System.String)fieldValue; break;
			case 1: this.joints = (IList<org.robokind.avrogen.motion.SynchronizedJointConfigRecord>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
