// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by RoboKindChat.vshost.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.robokind.avrogen.speech
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class SpeechEventListRecord : ISpecificRecord, SpeechEventList
	{
		private static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""SpeechEventListRecord"",""namespace"":""org.robokind.avrogen.speech"",""fields"":[{""name"":""speechServiceId"",""type"":""string""},{""name"":""timestampMillisecUTC"",""type"":""long""},{""name"":""speechEvents"",""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""SpeechEventRecord"",""namespace"":""org.robokind.avrogen.speech"",""fields"":[{""name"":""eventType"",""type"":""string""},{""name"":""streamNumber"",""type"":""long""},{""name"":""textPosition"",""type"":""int""},{""name"":""textLength"",""type"":""int""},{""name"":""currentData"",""type"":""int""},{""name"":""nextData"",""type"":""int""},{""name"":""stringData"",""type"":""string""},{""name"":""duration"",""type"":""int""}]}}}]}");
		private string _speechServiceId;
		private long _timestampMillisecUTC;
		private IList<org.robokind.avrogen.speech.SpeechEventRecord> _speechEvents;
		public virtual Schema Schema
		{
			get
			{
				return SpeechEventListRecord._SCHEMA;
			}
		}
		public string speechServiceId
		{
			get
			{
				return this._speechServiceId;
			}
			set
			{
				this._speechServiceId = value;
			}
		}
		public long timestampMillisecUTC
		{
			get
			{
				return this._timestampMillisecUTC;
			}
			set
			{
				this._timestampMillisecUTC = value;
			}
		}
		public IList<org.robokind.avrogen.speech.SpeechEventRecord> speechEvents
		{
			get
			{
				return this._speechEvents;
			}
			set
			{
				this._speechEvents = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.speechServiceId;
			case 1: return this.timestampMillisecUTC;
			case 2: return this.speechEvents;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.speechServiceId = (System.String)fieldValue; break;
			case 1: this.timestampMillisecUTC = (System.Int64)fieldValue; break;
			case 2: this.speechEvents = (IList<org.robokind.avrogen.speech.SpeechEventRecord>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
