// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by RoboKindChat.vshost.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.robokind.avrogen.speechrec
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class SpeechRecEventRecord : ISpecificRecord, SpeechRecEvent
	{
		private static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""SpeechRecEventRecord"",""namespace"":""org.robokind.avrogen.speechrec"",""fields"":[{""name"":""recognizerId"",""type"":""string""},{""name"":""timestampMillisecUTC"",""type"":""long""},{""name"":""recognizedText"",""type"":""string""},{""name"":""confidence"",""type"":""double""}]}");
		private string _recognizerId;
		private long _timestampMillisecUTC;
		private string _recognizedText;
		private double _confidence;
		public virtual Schema Schema
		{
			get
			{
				return SpeechRecEventRecord._SCHEMA;
			}
		}
		public string recognizerId
		{
			get
			{
				return this._recognizerId;
			}
			set
			{
				this._recognizerId = value;
			}
		}
		public long timestampMillisecUTC
		{
			get
			{
				return this._timestampMillisecUTC;
			}
			set
			{
				this._timestampMillisecUTC = value;
			}
		}
		public string recognizedText
		{
			get
			{
				return this._recognizedText;
			}
			set
			{
				this._recognizedText = value;
			}
		}
		public double confidence
		{
			get
			{
				return this._confidence;
			}
			set
			{
				this._confidence = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.recognizerId;
			case 1: return this.timestampMillisecUTC;
			case 2: return this.recognizedText;
			case 3: return this.confidence;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.recognizerId = (System.String)fieldValue; break;
			case 1: this.timestampMillisecUTC = (System.Int64)fieldValue; break;
			case 2: this.recognizedText = (System.String)fieldValue; break;
			case 3: this.confidence = (System.Double)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
